/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Coffee_Management_System2;


import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;



/**
 *
 * @author guna3
 */
public class Coffee_Management_System2 extends javax.swing.JFrame {
double [] drink=new double[5];
double [] cake=new double[8];
double [] cost=new double[3];
double [] i = new double[13];


    /**
     * Creates new form Coffee_Management_System2
     */
    public Coffee_Management_System2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtLattle = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jChkLattle = new javax.swing.JCheckBox();
        jChkIcedLattle = new javax.swing.JCheckBox();
        jChkEspresso = new javax.swing.JCheckBox();
        jChkCappuccino = new javax.swing.JCheckBox();
        jChkIcedCappuccino = new javax.swing.JCheckBox();
        jtxtIcedLattle = new javax.swing.JTextField();
        jtxtEspresso = new javax.swing.JTextField();
        jtxtCappuccino = new javax.swing.JTextField();
        jtxtIcedCappuccino = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jlbl = new javax.swing.JLabel();
        jlblCostCake1 = new javax.swing.JLabel();
        jlblService1 = new javax.swing.JLabel();
        jlblCostDrinks = new javax.swing.JLabel();
        jlblCostCake = new javax.swing.JLabel();
        jlblService = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jChkCoffee = new javax.swing.JCheckBox();
        jChkRedVelvet = new javax.swing.JCheckBox();
        jChkBoston = new javax.swing.JCheckBox();
        jChkLagos = new javax.swing.JCheckBox();
        jChkKilburn = new javax.swing.JCheckBox();
        jChkCarlton = new javax.swing.JCheckBox();
        jChkQueens = new javax.swing.JCheckBox();
        jtxtCoffee = new javax.swing.JTextField();
        jtxtRedVelvet = new javax.swing.JTextField();
        jtxtBoston = new javax.swing.JTextField();
        jtxtBlack = new javax.swing.JTextField();
        jtxtLagos = new javax.swing.JTextField();
        jtxtKilburn = new javax.swing.JTextField();
        jtxtCarlton = new javax.swing.JTextField();
        jtxtQueens = new javax.swing.JTextField();
        jChkBlack = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jBtnTotal = new javax.swing.JButton();
        jBtnReceipt = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Coffee Management System");

        jtxtLattle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtLattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLattle.setText("0");
        jtxtLattle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLattleMouseClicked(evt);
            }
        });
        jtxtLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLattleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jtxtLattle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jtxtLattle)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jChkLattle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkLattle.setText("Latttle");
        jChkLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkLattleMouseClicked(evt);
            }
        });
        jChkLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLattleActionPerformed(evt);
            }
        });

        jChkIcedLattle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkIcedLattle.setText("Iced Lattle");
        jChkIcedLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkIcedLattleMouseClicked(evt);
            }
        });

        jChkEspresso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkEspresso.setText("Espresso");
        jChkEspresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkEspressoMouseClicked(evt);
            }
        });

        jChkCappuccino.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkCappuccino.setText("Cappuccino");
        jChkCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCappuccinoMouseClicked(evt);
            }
        });
        jChkCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCappuccinoActionPerformed(evt);
            }
        });

        jChkIcedCappuccino.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkIcedCappuccino.setText("Iced Cappuccino");
        jChkIcedCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkIcedCappuccinoMouseClicked(evt);
            }
        });
        jChkIcedCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkIcedCappuccinoActionPerformed(evt);
            }
        });

        jtxtIcedLattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtIcedLattle.setText("0");
        jtxtIcedLattle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtIcedLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtIcedLattleMouseClicked(evt);
            }
        });

        jtxtEspresso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtEspresso.setText("0");
        jtxtEspresso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jtxtEspresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtEspressoMouseClicked(evt);
            }
        });

        jtxtCappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCappuccino.setText("0");
        jtxtCappuccino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCappuccinoMouseClicked(evt);
            }
        });

        jtxtIcedCappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtIcedCappuccino.setText("0");
        jtxtIcedCappuccino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtIcedCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtIcedCappuccinoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChkIcedLattle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jChkLattle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jChkEspresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jChkCappuccino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jChkIcedCappuccino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtIcedCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtIcedLattle)
                            .addComponent(jtxtEspresso)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jChkLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jChkIcedLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jtxtIcedLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtEspresso, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jChkEspresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkIcedCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtIcedCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 380, 350));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbl.setText("Cost of Drinks");

        jlblCostCake1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostCake1.setText("Cost of cake");

        jlblService1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblService1.setText("Service charge");

        jlblCostDrinks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblCostDrinks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostDrinks.setText("0");
        jlblCostDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblCostCake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblCostCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostCake.setText("0");
        jlblCostCake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblService.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblService.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblService.setText("10");
        jlblService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblService1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblCostCake1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblCostCake, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jlblService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jlblCostDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblCostCake1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostCake, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblService1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblService, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 380, 150));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jChkCoffee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkCoffee.setText("Coffee Cake");
        jChkCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCoffeeMouseClicked(evt);
            }
        });

        jChkRedVelvet.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkRedVelvet.setText("Red Velvet Cake");
        jChkRedVelvet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkRedVelvetMouseClicked(evt);
            }
        });

        jChkBoston.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkBoston.setText("Boston Cream Cake");
        jChkBoston.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkBostonMouseClicked(evt);
            }
        });

        jChkLagos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkLagos.setText("Lagos chocolate Cake");
        jChkLagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkLagosMouseClicked(evt);
            }
        });

        jChkKilburn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkKilburn.setText("Kilburn Chocolate Cake");
        jChkKilburn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jChkKilburn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkKilburnMouseClicked(evt);
            }
        });

        jChkCarlton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkCarlton.setText("Carlton Hill Chocolate Cake");
        jChkCarlton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCarltonMouseClicked(evt);
            }
        });

        jChkQueens.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkQueens.setText("Queen's Park Chocolate Cake");
        jChkQueens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkQueensMouseClicked(evt);
            }
        });

        jtxtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoffee.setText("0");
        jtxtCoffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCoffeeMouseClicked(evt);
            }
        });

        jtxtRedVelvet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtRedVelvet.setText("0");
        jtxtRedVelvet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtRedVelvet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtRedVelvetMouseClicked(evt);
            }
        });

        jtxtBoston.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBoston.setText("0");
        jtxtBoston.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtBoston.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBostonMouseClicked(evt);
            }
        });

        jtxtBlack.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBlack.setText("0");
        jtxtBlack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBlackMouseClicked(evt);
            }
        });

        jtxtLagos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLagos.setText("0");
        jtxtLagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtLagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLagosMouseClicked(evt);
            }
        });

        jtxtKilburn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtKilburn.setText("0");
        jtxtKilburn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtKilburn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtKilburnMouseClicked(evt);
            }
        });

        jtxtCarlton.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCarlton.setText("0");
        jtxtCarlton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtCarlton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCarltonMouseClicked(evt);
            }
        });

        jtxtQueens.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtQueens.setText("0");
        jtxtQueens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtQueens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtQueensMouseClicked(evt);
            }
        });

        jChkBlack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkBlack.setText("Black Forest Cake");
        jChkBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkBlackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jChkCarlton, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addComponent(jChkLagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jChkKilburn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtKilburn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jChkBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jChkQueens, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtQueens, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jChkBoston, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jChkCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jChkRedVelvet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtRedVelvet, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtBoston, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtRedVelvet, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkRedVelvet, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkBoston, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtBoston, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtKilburn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkKilburn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkQueens, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtQueens, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 460, 350));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 400, 430));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jBtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnTotal.setText("Total");
        jBtnTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });

        jBtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnReceipt.setText("Receipt");
        jBtnReceipt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jBtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceiptActionPerformed(evt);
            }
        });

        jBtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        jBtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jBtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnExit)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnExit)
                    .addComponent(jBtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnReset))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 570, 400, 70));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Tax");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Sub Total");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Total");

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTax.setText("0");
        jlblTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSubTotal.setText("0");
        jlblSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTotal.setText("0");
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 460, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        jlblCostCake.setText("0");
         jlblCostDrinks.setText("0");
          jlblService.setText("0");
           jlblTax.setText("0");
            jlblSubTotal.setText("0");
             jlblTotal.setText("0");
            jtxtLattle.setText("0");
            jtxtIcedLattle.setText("0");
            jtxtEspresso.setText("0");
            jtxtCappuccino.setText("0");
            jtxtIcedCappuccino.setText("0");
            jtxtCoffee.setText("0");
            jtxtRedVelvet.setText("0");
            jtxtBoston.setText("0");
            jtxtBlack.setText("0");
            jtxtLagos.setText("0");
            jtxtKilburn.setText("0");
            jtxtCarlton.setText("0");
            jtxtQueens.setText("0");
            jtxtReceipt.setText(null);
            jChkLattle.setSelected(false);
            jChkIcedLattle.setSelected(false);
            jChkEspresso.setSelected(false);
            jChkCappuccino.setSelected(false);
            jChkIcedCappuccino.setSelected(false);
            jChkCoffee.setSelected(false);
            jChkRedVelvet.setSelected(false);
            jChkBlack.setSelected(false);
            jChkKilburn.setSelected(false);
            jChkLagos.setSelected(false);
            jChkBoston.setSelected(false);
            jChkCarlton.setSelected(false);
            jChkQueens.setSelected(false);

              
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jBtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceiptActionPerformed
        drink[0]=Double.parseDouble(jtxtLattle.getText());
        drink[1]=Double.parseDouble(jtxtIcedLattle.getText());
        drink[2]=Double.parseDouble(jtxtEspresso.getText());
        drink[3]=Double.parseDouble(jtxtCappuccino.getText());
        drink[4]=Double.parseDouble(jtxtIcedCappuccino.getText());
        
        cake[0]=Double.parseDouble(jtxtCoffee.getText());
        cake[1]=Double.parseDouble(jtxtRedVelvet.getText());
        cake[2]=Double.parseDouble(jtxtBlack.getText());
        cake[3]=Double.parseDouble(jtxtLagos.getText());
        cake[4]=Double.parseDouble(jtxtBoston.getText());
        cake[5]=Double.parseDouble(jtxtKilburn.getText());
        cake[6]=Double.parseDouble(jtxtCarlton.getText());
        cake[7]=Double.parseDouble(jtxtQueens.getText());
        
        cost[0]=Double.parseDouble(jlblTax.getText());
        cost[1]=Double.parseDouble(jlblSubTotal.getText());
        cost[2]=Double.parseDouble(jlblTotal.getText());
        
       

        
        
        int refs=1325+(int)(Math.random()*4238);
        
        
        Calendar time=Calendar.getInstance();
        time.getTime();
        SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
        tTime.format(time.getTime());
        SimpleDateFormat Tdate=new SimpleDateFormat("dd-MM-yyyy");
        Tdate.format(time.getTime());
        
        
        
        jtxtReceipt.append("\t\n\t Cafe Management System\n\n"+
                "Reference:\t\t\t"+refs+
                "\n=========================================="+
                "\nLattle:\t\t\t"+drink[0]+
                "\nIced Lattle\t\t\t"+drink[1]+
                "\nEspress\t\t\t"+drink[2]+
                "\nCappuccino\t\t\t"+drink[3]+
                "\nIcedCappuccino\t\t"+drink[4]+
                "\n=========================================="+
                "\nCoffee\t\t\t"+cake[0]+
                "\nRed Velvet Cake \t\t"+cake[1]+
                "\nBlack Forest Cake\t\t"+cake[2]+
                "\nBoston cream Pie\t\t"+cake[3]+
                "\nLagos Chocolate cake\t\t"+cake[4]+
                "\nKilburn Chocolate Cake\t\t"+cake[5]+
                "\nCarlton Hill Chocolate Cake\t\t"+cake[6]+
                "\nQueen's Park Chocolate cake\t"+cake[7]+
                "\n=========================================="+
                "\nTax:\t\t\t"+cost[0]+
                "\nSub Total:\t\t\t"+cost[1]+
                "\nTotal:\t\t\t"+cost[2]+
                "\n=========================================="+
                "\nDate: "+Tdate.format(time.getTime())+
                "\tTime: "+tTime.format(time.getTime())+
                "\n\n\n\t\tThank You"
                );
        


    }//GEN-LAST:event_jBtnReceiptActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jChkLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLattleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkLattleActionPerformed

 
    private void jChkCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCappuccinoActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jChkCappuccinoActionPerformed

    private void jtxtLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLattleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLattleActionPerformed

    private void jChkIcedCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkIcedCappuccinoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jChkIcedCappuccinoActionPerformed

    private void jChkLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkLattleMouseClicked
      double cLattle=Double.parseDouble(jlblCostDrinks.getText());
      double Lattle=Double.parseDouble(jtxtLattle.getText());
      double iLattle=75;
        
        if(jChkLattle.isSelected())
        {
            i[1]=(Lattle * iLattle)+cLattle;
            String pDrink=String.format("%.2f",i[1]);
            jlblCostDrinks.setText(pDrink);
           
        
        }
    }//GEN-LAST:event_jChkLattleMouseClicked

    private void jChkIcedLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkIcedLattleMouseClicked
        double cIcedLattle=Double.parseDouble(jlblCostDrinks.getText());
        double IcedLattle=Double.parseDouble(jtxtIcedLattle.getText());
        double iIcedLattle=100;
        
        if(jChkIcedLattle.isSelected())
        {
            i[2]=(IcedLattle*iIcedLattle)+cIcedLattle;
            String pDrink=String.format("%.2f",i[2]);
            jlblCostDrinks.setText(pDrink);
            
        
        }
    }//GEN-LAST:event_jChkIcedLattleMouseClicked

    private void jChkEspressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkEspressoMouseClicked
        double cEspresso=Double.parseDouble(jlblCostDrinks.getText());
        double Espresso =Double.parseDouble(jtxtEspresso.getText());
        double iEspresso=65;
        
        if(jChkEspresso.isSelected())
        {
            i[3]=(Espresso * iEspresso)+cEspresso;
            String pDrink=String.format("%.2f",i[3]);
            jlblCostDrinks.setText(pDrink);
            
        
        }
    }//GEN-LAST:event_jChkEspressoMouseClicked

    private void jChkCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCappuccinoMouseClicked
        double cCap=Double.parseDouble(jlblCostDrinks.getText());
        double Cappuccino =Double.parseDouble(jtxtCappuccino.getText());
        double iCappuccino=90;
        
        if(jChkCappuccino.isSelected())
        {
            i[0]=(Cappuccino * iCappuccino)+cCap;
            String pDrink=String.format("%.2f",i[0]);
            jlblCostDrinks.setText(pDrink);
           
        
        }
    }//GEN-LAST:event_jChkCappuccinoMouseClicked

    private void jChkIcedCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkIcedCappuccinoMouseClicked
        double cIcedCappuccino=Double.parseDouble(jlblCostDrinks.getText());
        double IcedCappuccino =Double.parseDouble(jtxtIcedCappuccino.getText());
        double iIcedCappuccino=120;
        
        if(jChkIcedCappuccino.isSelected())
        {
            i[4]=(IcedCappuccino * iIcedCappuccino)+cIcedCappuccino;
            String pDrink=String.format("%.2f",i[4]);
            jlblCostDrinks.setText(pDrink);
          
        }
    }//GEN-LAST:event_jChkIcedCappuccinoMouseClicked

    private void jChkCoffeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCoffeeMouseClicked
        double cCoffee=Double.parseDouble(jlblCostCake.getText());
        double Coffee=Double.parseDouble(jtxtCoffee.getText());
        double iCoffee=50;
        
        if(jChkCoffee.isSelected())
        {
            i[5]=(Coffee* iCoffee)+cCoffee;
            var pDrink=String.format("%.2f",i[5]);
            jlblCostCake.setText(pDrink);
          
        }
    }//GEN-LAST:event_jChkCoffeeMouseClicked

    private void jChkRedVelvetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkRedVelvetMouseClicked
        double cRedVelvet=Double.parseDouble(jlblCostCake.getText());
        double RedVelvet=Double.parseDouble(jtxtRedVelvet.getText());
        double iRedVelvet=110;
        
        if(jChkRedVelvet.isSelected())
        {
            i[6]=(RedVelvet* iRedVelvet)+cRedVelvet;
            var pDrink=String.format("%.2f",i[6]);
            jlblCostCake.setText(pDrink);
          
        }
    }//GEN-LAST:event_jChkRedVelvetMouseClicked

    private void jChkBostonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkBostonMouseClicked
        double cBoston=Double.parseDouble(jlblCostCake.getText());
        double Boston=Double.parseDouble(jtxtBoston.getText());
        double iBoston=135;
        
        if(jChkBoston.isSelected())
        {
            i[7]=(Boston* iBoston)+cBoston;
            var pDrink=String.format("%.2f",i[7]);
            jlblCostCake.setText(pDrink);
          
        }
    }//GEN-LAST:event_jChkBostonMouseClicked

    private void jChkBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkBlackMouseClicked
        double cBlack=Double.parseDouble(jlblCostCake.getText());
        double Black=Double.parseDouble(jtxtBlack.getText());
        double iBlack=110;
        
        if(jChkBlack.isSelected())
        {
            i[8]=(Black* iBlack)+cBlack;
            var pDrink=String.format("%.2f",i[8]);
            jlblCostCake.setText(pDrink);
          
        }
    }//GEN-LAST:event_jChkBlackMouseClicked

    private void jChkLagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkLagosMouseClicked
        double cLagos=Double.parseDouble(jlblCostCake.getText());
        double Lagos=Double.parseDouble(jtxtLagos.getText());
        double iLagos=80;
        
        if(jChkLagos.isSelected())
        {
            i[9]=(Lagos* iLagos)+cLagos;
            var pDrink=String.format("%.2f",i[9]);
            jlblCostCake.setText(pDrink);
          
        }
    }//GEN-LAST:event_jChkLagosMouseClicked

    private void jChkKilburnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkKilburnMouseClicked
        double cKilburn=Double.parseDouble(jlblCostCake.getText());
        double Kilburn=Double.parseDouble(jtxtKilburn.getText());
        double iKilburn=130;
        
        if(jChkKilburn.isSelected())
        {
            i[10]=(Kilburn* iKilburn)+cKilburn;
            var pDrink=String.format("%.2f",i[10]);
            jlblCostCake.setText(pDrink);
          
        }
    }//GEN-LAST:event_jChkKilburnMouseClicked

    private void jChkCarltonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCarltonMouseClicked
        double cCarlton=Double.parseDouble(jlblCostCake.getText());
        double Carlton=Double.parseDouble(jtxtCarlton.getText());
        double iCarlton=125;
        
        if(jChkCarlton.isSelected())
        {
            i[11]=(Carlton* iCarlton)+cCarlton;
            var pDrink=String.format("%.2f",i[11]);
            jlblCostCake.setText(pDrink);
          
        }
    }//GEN-LAST:event_jChkCarltonMouseClicked

    private void jChkQueensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkQueensMouseClicked
        double cQueens=Double.parseDouble(jlblCostCake.getText());
        double Queens=Double.parseDouble(jtxtQueens.getText());
        double iQueens=75;
        
        if(jChkQueens.isSelected())
        {
            i[12]=(Queens* iQueens)+cQueens;
            var pDrink=String.format("%.2f",i[12]);
            jlblCostCake.setText(pDrink);
          
        }
    }//GEN-LAST:event_jChkQueensMouseClicked

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
        // TODO add your handling code here:
        drink[0]=Double.parseDouble(jlblCostDrinks.getText());
        drink[1]=Double.parseDouble(jlblCostCake.getText());
        drink[2]=Double.parseDouble(jlblService.getText());
       

        
        double cTotal1 =(drink[0]+drink[1]+drink[2]);
        
        String iTaxTotal=String.format("%.2f",cTotal1/100);
        jlblTax.setText(iTaxTotal);
        
        double subTotal=(cTotal1);
        String isubTotal=String.format("%.2f", subTotal);
        jlblSubTotal.setText(isubTotal);
      
        double allTotal=(cTotal1);
        String iTotal=String.format("%.2f", allTotal+(allTotal/100));
        jlblTotal.setText(iTotal);
        
        String CostD=String.format("%.2f",drink[0]);
        jlblCostDrinks.setText(CostD);
        
        String CostC=String.format("%.2f",drink[1]);
        jlblCostCake.setText(CostC);
        
        String Service=String.format("%.2f",drink[2]);
        jlblService.setText(Service);
       

    }//GEN-LAST:event_jBtnTotalActionPerformed

    private void jtxtLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLattleMouseClicked
       jtxtLattle.setText(null);
    }//GEN-LAST:event_jtxtLattleMouseClicked

    private void jtxtIcedLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIcedLattleMouseClicked
        jtxtIcedLattle.setText(null);
    }//GEN-LAST:event_jtxtIcedLattleMouseClicked

    private void jtxtEspressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEspressoMouseClicked
        jtxtEspresso.setText(null);
    }//GEN-LAST:event_jtxtEspressoMouseClicked

    private void jtxtCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCappuccinoMouseClicked
       jtxtEspresso.setText(null);
    }//GEN-LAST:event_jtxtCappuccinoMouseClicked

    private void jtxtIcedCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIcedCappuccinoMouseClicked
        jtxtIcedCappuccino.setText(null);
    }//GEN-LAST:event_jtxtIcedCappuccinoMouseClicked

    private void jtxtCoffeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCoffeeMouseClicked
        jtxtCoffee.setText(null);
    }//GEN-LAST:event_jtxtCoffeeMouseClicked

    private void jtxtRedVelvetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtRedVelvetMouseClicked
        jtxtRedVelvet.setText(null);
    }//GEN-LAST:event_jtxtRedVelvetMouseClicked

    private void jtxtBostonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBostonMouseClicked
        jtxtBoston.setText(null);    }//GEN-LAST:event_jtxtBostonMouseClicked

    private void jtxtBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBlackMouseClicked
        jtxtBlack.setText(null);
    }//GEN-LAST:event_jtxtBlackMouseClicked

    private void jtxtLagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLagosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLagosMouseClicked

    private void jtxtKilburnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtKilburnMouseClicked
        jtxtKilburn.setText(null);
    }//GEN-LAST:event_jtxtKilburnMouseClicked

    private void jtxtCarltonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCarltonMouseClicked
        jtxtCarlton.setText(null);
    }//GEN-LAST:event_jtxtCarltonMouseClicked

    private void jtxtQueensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtQueensMouseClicked
       jtxtQueens.setText(null);
    }//GEN-LAST:event_jtxtQueensMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coffee_Management_System2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coffee_Management_System2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coffee_Management_System2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coffee_Management_System2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coffee_Management_System2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnReceipt;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JCheckBox jChkBlack;
    private javax.swing.JCheckBox jChkBoston;
    private javax.swing.JCheckBox jChkCappuccino;
    private javax.swing.JCheckBox jChkCarlton;
    private javax.swing.JCheckBox jChkCoffee;
    private javax.swing.JCheckBox jChkEspresso;
    private javax.swing.JCheckBox jChkIcedCappuccino;
    private javax.swing.JCheckBox jChkIcedLattle;
    private javax.swing.JCheckBox jChkKilburn;
    private javax.swing.JCheckBox jChkLagos;
    private javax.swing.JCheckBox jChkLattle;
    private javax.swing.JCheckBox jChkQueens;
    private javax.swing.JCheckBox jChkRedVelvet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbl;
    private javax.swing.JLabel jlblCostCake;
    private javax.swing.JLabel jlblCostCake1;
    private javax.swing.JLabel jlblCostDrinks;
    private javax.swing.JLabel jlblService;
    private javax.swing.JLabel jlblService1;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JTextField jtxtBlack;
    private javax.swing.JTextField jtxtBoston;
    private javax.swing.JTextField jtxtCappuccino;
    private javax.swing.JTextField jtxtCarlton;
    private javax.swing.JTextField jtxtCoffee;
    private javax.swing.JTextField jtxtEspresso;
    private javax.swing.JTextField jtxtIcedCappuccino;
    private javax.swing.JTextField jtxtIcedLattle;
    private javax.swing.JTextField jtxtKilburn;
    private javax.swing.JTextField jtxtLagos;
    private javax.swing.JTextField jtxtLattle;
    private javax.swing.JTextField jtxtQueens;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtRedVelvet;
    // End of variables declaration//GEN-END:variables
}
